// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd-PwiPh6Go8_Mpx7EuXgNtitAXMKWcVE',
    appId: '1:1041332123597:web:173ce06d83facc56f4f684',
    messagingSenderId: '1041332123597',
    projectId: 'diariotreinos',
    authDomain: 'diariotreinos.firebaseapp.com',
    storageBucket: 'diariotreinos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMlSvNuWdm7du3cvnDmo3huP4blKJZS9o',
    appId: '1:1041332123597:android:4ae59f89cea43acff4f684',
    messagingSenderId: '1041332123597',
    projectId: 'diariotreinos',
    storageBucket: 'diariotreinos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxEtSbHOdRQIKF_6WX2f9h8TCWitny1_M',
    appId: '1:1041332123597:ios:d596be21897dc5cbf4f684',
    messagingSenderId: '1041332123597',
    projectId: 'diariotreinos',
    storageBucket: 'diariotreinos.firebasestorage.app',
    iosBundleId: 'com.example.diarioTreinos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxEtSbHOdRQIKF_6WX2f9h8TCWitny1_M',
    appId: '1:1041332123597:ios:d596be21897dc5cbf4f684',
    messagingSenderId: '1041332123597',
    projectId: 'diariotreinos',
    storageBucket: 'diariotreinos.firebasestorage.app',
    iosBundleId: 'com.example.diarioTreinos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd-PwiPh6Go8_Mpx7EuXgNtitAXMKWcVE',
    appId: '1:1041332123597:web:5482aa02bb0dd4aef4f684',
    messagingSenderId: '1041332123597',
    projectId: 'diariotreinos',
    authDomain: 'diariotreinos.firebaseapp.com',
    storageBucket: 'diariotreinos.firebasestorage.app',
  );
}
